# Support Vector Regression (SVR)

## Importing the libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Importing the dataset

In [ ]:
pd.options.display.float_format = '{:,.2f}'.format

In [ ]:
dataset = pd.read_csv('Data.csv')
dataset.describe()

AT        V       AP       RH       PE
count 9,568.00 9,568.00 9,568.00 9,568.00 9,568.00
mean     19.65    54.31 1,013.26    73.31   454.37
std       7.45    12.71     5.94    14.60    17.07
min       1.81    25.36   992.89    25.56   420.26
25%      13.51    41.74 1,009.10    63.33   439.75
50%      20.34    52.08 1,012.94    74.97   451.55
75%      25.72    66.54 1,017.26    84.83   468.43
max      37.11    81.56 1,033.30   100.16   495.76

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9568 entries, 0 to 9567
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   AT      9568 non-null   float64
 1   V       9568 non-null   float64
 2   AP      9568 non-null   float64
 3   RH      9568 non-null   float64
 4   PE      9568 non-null   float64
dtypes: float64(5)
memory usage: 373.9 KB


In [ ]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
y = y.reshape(len(y), 1)
print(y)

[[463.26]
 [444.37]
 [488.56]
 ...
 [429.57]
 [435.74]
 [453.28]]


##Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
s_c = StandardScaler()
X = sc.fit_transform(X)
y = s_c.fit_transform(y)
print(y)

[[ 0.52120807]
 [-0.58566442]
 [ 2.00367889]
 ...
 [-1.45288056]
 [-1.09134518]
 [-0.06357687]]


## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.8, random_state = 0)
print(X_train)
print(y_test)

[[-1.13139243e+00 -8.79483939e-01  6.70361150e-01  5.19950626e-01]
 [-8.02625329e-01 -4.56725914e-04  4.48081799e-01  1.44595454e-01]
 [ 1.76980952e+00  1.86068863e+00  2.39273924e-01 -1.88424035e+00]
 ...
 [-3.81266673e-01 -1.24226957e+00  8.42122466e-01  1.30211405e-01]
 [-9.19371198e-01 -1.03451381e+00  1.54432314e+00  8.82291659e-01]
 [ 1.70003038e+00  1.06980022e+00 -1.20890972e+00 -2.42329969e+00]]
[[-1.35561172]
 [ 0.33077209]
 [ 0.39698521]
 ...
 [ 1.10716492]
 [-0.95891893]
 [ 0.52237998]]


## Training the SVR model on the Training set

In [ ]:
from sklearn.svm import SVR
regressor = SVR(kernel= "rbf")
regressor.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

## Predicting the Test set results

In [ ]:
l = regressor.predict(X_test)
y_pred = s_c.inverse_transform(l.reshape(1,-1))

## Evaluating the Model Performance

In [ ]:
from sklearn.metrics import r2_score
r2_score(s_c.inverse_transform(y_test), y_pred[0])

0.94807576744016

AT = Ambient Temperature
V = Exhaust Vacuum
AP = Ambient Pressure
RH = Ralative Humididty